'use strict';
// National Enterprise Business Center — Morgan Advisor
const MODEL=process.env.ASSISTANT_MODEL||'gpt-4o-mini',REQUIRED_CLOSE='Do you have any further questions for me?';
const DEPARTMENTS={funding:{label:'Business Funding Opportunity Center →',href:'/business-funding.html',primary:true},planning:{label:'Business Assessment & Planning →',href:'/assessment.html'},documents:{label:'Business Documents →',href:'/documents.html'},'website-advisory':{label:'Website Design Advisory →',href:'/website-builder.html'},federal:{label:'Registered Federal Contractors Portal →',href:'https://rfcp.aproposgroupllc.com',blank:true},state:{label:'National Corporate Contract Exchange →',href:'https://natcorp.aproposgroupllc.com',blank:true}};
const ROUTING=`When an action requires another NEBC service/platform, end with [[OPEN: id]] using only funding, planning, documents, website-advisory, federal, or state. The UI renders the tag as a safe action button. Never type or invent a URL in prose when a routing id exists. Federal registration/readiness applies ONLY when federal intent is explicitly established. State/local intent alone routes to state/NAT-CORP and must never create a SAM.gov or Registered Federal Contractor priority.`;
const FUNDING=`For funding: use known assessment and saved funding-profile facts first. Funding interest is not provider eligibility. When enough evidence exists, use exactly one classification: FUNDING READY FOR FURTHER EVALUATION; FUNDING PREPARATION REQUIRED; EARLY-STAGE FUNDING DEVELOPMENT; SPECIALIST REVIEW REQUIRED. Consider Business Foundation, Financial Foundation, Business Planning, Management Capacity, and Opportunity-Specific Documentation as ESTABLISHED, GAP, UNKNOWN, or NOT APPLICABLE. Never silently convert unknown to established. If source identification is requested, explain readiness first then use [[OPEN: funding]]. Never promise approval, eligibility, lender acceptance, grant award, investment, or underwriting outcome.`;
const KNOWLEDGE=`You are Morgan, NEBC's professional post-assessment Business Development Advisor. Interpret the member's actual assessment evidence, identify one primary next step, and route only when action is required. ${ROUTING} ${FUNDING} For procurement: RFCP is the federal opportunity path; NAT-CORP is the state/local opportunity path. Do not use retired CapGen/NGCC names. For tax/accounting/legal determinations recommend a qualified professional. Close completed advisory responses with exactly: ${REQUIRED_CLOSE}`;
function actionsFrom(text){const m=String(text||'').match(/\[\[OPEN:\s*([^\]]+)\]\]/i);if(!m)return{text:String(text||''),actions:[]};const ids=m[1].split(',').map(x=>x.trim()).filter(Boolean).slice(0,3),actions=ids.map(id=>DEPARTMENTS[id]).filter(Boolean);return{text:String(text).replace(/\n?\[\[OPEN:[^\]]+\]\]/ig,'').trim(),actions}}
function fallback(msg,context){const q=String(msg||'').toLowerCase();let reply;if(q.includes('fund'))reply=`I can use your assessment and saved Funding profile to evaluate preparation, but NEBC does not determine provider eligibility or approval. If you want controlled source screening, continue to the Business Funding Opportunity Center.\n[[OPEN: funding]]`;else if(q.includes('state')||q.includes('local contract'))reply=`For state and local opportunities, use NAT-CORP. Federal registration is not a prerequisite unless you also choose the federal opportunity path.\n[[OPEN: state]]`;else if(q.includes('federal')||q.includes('sam'))reply=`For federal opportunities, confirm federal registration readiness and use the Registered Federal Contractors Portal.\n[[OPEN: federal]]`;else reply=`I’ll use the assessment context to identify one controlling next step. ${context?'Your saved profile is available for this review.':'Complete or restore your assessment profile for a personalized recommendation.'}`;if(!reply.includes(REQUIRED_CLOSE))reply+=`\n\n${REQUIRED_CLOSE}`;return reply}
exports.handler=async event=>{const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*'};if(event.httpMethod==='OPTIONS')return{statusCode:204,headers};if(event.httpMethod!=='POST')return{statusCode:405,headers,body:JSON.stringify({error:'POST only'})};let b;try{b=JSON.parse(event.body||'{}')}catch{return{statusCode:400,headers,body:JSON.stringify({error:'Bad JSON'})}}const messages=Array.isArray(b.messages)?b.messages.slice(-16):[],last=messages.filter(x=>x.role==='user').at(-1)?.content||'',context=String(b.context||'').slice(0,6000);let reply='';try{if(process.env.OPENAI_API_KEY){const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:MODEL,temperature:.2,max_tokens:1200,messages:[{role:'system',content:KNOWLEDGE},{role:'system',content:`MEMBER / ASSESSMENT CONTEXT:\n${context||'No saved context supplied.'}`},...messages]})}),d=await r.json();if(!r.ok)throw Error('assistant unavailable');reply=d?.choices?.[0]?.message?.content?.trim()||''}if(!reply)reply=fallback(last,context)}catch(_){reply=fallback(last,context)}if(!reply.includes(REQUIRED_CLOSE))reply+=`\n\n${REQUIRED_CLOSE}`;const parsed=actionsFrom(reply);return{statusCode:200,headers,body:JSON.stringify({ok:true,reply:parsed.text,actions:parsed.actions})}};
